 "use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../lib/supabase";
import {BarChart3,CheckCircle2,ArrowUpRight,Users,Target,LogOut} from "lucide-react";
import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer} from "recharts";

const nav=[["dashboard","Dashboard"],["checkin","Daily Check-in"],["trades","Trade Journal"],["clients","Clients & Revenue"],["goals","Plan & Goals"]];
const money=n=>`${n<0?"-$":"$"}${Math.abs(Number(n||0)).toLocaleString(undefined,{maximumFractionDigits:2})}`;
const today=()=>new Date().toISOString().slice(0,10), month=()=>today().slice(0,7);
export default function Dashboard(){
 const sb=supabase(); const [page,setPage]=useState("dashboard"); const [user,setUser]=useState(null);
 const [goals,setGoals]=useState({income:5000,proposals:20,start:100,target:10000,score:80,hours:25});
 const [checks,setChecks]=useState([]),[trades,setTrades]=useState([]),[clients,setClients]=useState([]),[loading,setLoading]=useState(true);
 const [form,setForm]=useState({}); const [message,setMessage]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await sb.auth.getUser();setUser(user);if(!user){setLoading(false);return}
   const [g,c,t,cl]=await Promise.all([sb.from("goals").select("*").eq("user_id",user.id).maybeSingle(),sb.from("daily_checkins").select("*").eq("user_id",user.id).order("date",{ascending:false}),sb.from("trades").select("*").eq("user_id",user.id).order("trade_date",{ascending:false}),sb.from("clients").select("*").eq("user_id",user.id).order("created_at",{ascending:false})]);
   if(g.data)setGoals(g.data);setChecks(c.data||[]);setTrades(t.data||[]);setClients(cl.data||[]);setLoading(false)})()},[]);
 const M=useMemo(()=>{let m=month(),cm=checks.filter(x=>x.date?.startsWith(m)),income=cm.reduce((a,x)=>a+Number(x.revenue||0),0),checkPL=cm.reduce((a,x)=>a+Number(x.trading_pl||0),0),tradePL=trades.reduce((a,x)=>a+Number(x.pl||0),0),pl=checkPL+tradePL,balance=Number(goals.start||0)+pl,on=clients.filter(x=>x.status==="Onboarded"),leads=clients.filter(x=>x.status==="Lead"),wins=trades.filter(x=>Number(x.pl)>0),viol=trades.filter(x=>x.followed_plan===false).length,ci=checks.find(x=>x.date===today()),score=ci?Math.round((ci.priority_done+ci.focus_done+ci.no_impulsive)/3*100):0;return{income,pl,balance,on,leads,wins,viol,ci,score,ip:Math.min(100,Math.round(income/Number(goals.income||1)*100)),tp:Math.min(100,Math.max(0,Math.round((balance-goals.start)/(goals.target-goals.start)*100))),proposals:cm.reduce((a,x)=>a+Number(x.proposals||0),0),convos:cm.reduce((a,x)=>a+Number(x.conversations||0),0)}},[checks,trades,clients,goals]);
 async function refresh(){const [c,t,cl,g]=await Promise.all([sb.from("daily_checkins").select("*").eq("user_id",user.id).order("date",{ascending:false}),sb.from("trades").select("*").eq("user_id",user.id).order("trade_date",{ascending:false}),sb.from("clients").select("*").eq("user_id",user.id).order("created_at",{ascending:false}),sb.from("goals").select("*").eq("user_id",user.id).maybeSingle()]);setChecks(c.data||[]);setTrades(t.data||[]);setClients(cl.data||[]);if(g.data)setGoals(g.data)}
 async function submit(e,type){e.preventDefault();setMessage("");let payload={...form};if(type==="checkin"){payload.date=today();payload.user_id=user.id;payload.priority_done=!!form.priority_done;payload.focus_done=!!form.focus_done;payload.no_impulsive=!!form.no_impulsive;delete payload.id;await sb.from("daily_checkins").upsert(payload,{onConflict:"user_id,date"})}
 if(type==="trade"){payload.user_id=user.id;payload.trade_date=today();payload.pl=Number(payload.pl||0);payload.followed_plan=payload.followed_plan==="true";await sb.from("trades").insert(payload)}
 if(type==="client"){payload.user_id=user.id;payload.value=Number(payload.value||0);payload.mrr=Number(payload.mrr||0);await sb.from("clients").insert(payload)}
 if(type==="goals"){payload.user_id=user.id;payload.income=Number(payload.income);payload.proposals=Number(payload.proposals);payload.start=Number(payload.start);payload.target=Number(payload.target);payload.score=Number(payload.score);payload.hours=Number(payload.hours);await sb.from("goals").upsert(payload,{onConflict:"user_id"})}
 setForm({});await refresh();setMessage("Saved.");}
 async function login(){let email=prompt("Enter your email");if(!email)return;let {error}=await sb.auth.signInWithOtp({email});alert(error?error.message:"Check your email for the login link.");}
 async function logout(){await sb.auth.signOut();location.reload()}
 if(loading)return <main className="main"><div className="card">Loading Growth OS…</div></main>;
 if(!user)return <main className="main" style={{marginLeft:0,maxWidth:600,margin:"80px auto"}}><div className="card"><div className="logo">Growth <span>OS</span></div><h1>Personal Growth Dashboard</h1><p className="muted">Sign in to sync your check-ins, trades, clients and goals across devices.</p><button className="btn" onClick={login}>Email me a sign-in link</button></div></main>;
 const Form=({children,type})=><form className="card" onSubmit={e=>submit(e,type)}>{children}<br/><button className="btn">Save</button>{message&&<span className="sub" style={{marginLeft:10}}>{message}</span>}</form>;
 return <div className="app"><aside className="side"><div className="logo">Growth <span>OS</span></div><div className="profile"><b>{user.email}</b><small>Freelancing + Trading</small></div><div className="nav">{nav.map(([id,label])=><button key={id} className={page===id?"active":""} onClick={()=>setPage(id)}>{label}</button>)}<button onClick={logout}><LogOut size={14}/> Sign out</button></div></aside>
 <main className="main">{page==="dashboard"&&<><div className="top"><div><h1>Good {new Date().getHours()<12?"morning":new Date().getHours()<18?"afternoon":"evening"}.</h1><p className="muted">{new Date().toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"})}</p></div><div className="actions"><button className="btn secondary" onClick={()=>setPage("checkin")}>Daily check-in</button><button className="btn" onClick={()=>setPage("trades")}>+ Log trade</button></div></div>
 <div className="grid4">{[[Target,"OVERALL PLAN",Math.round((M.ip+M.tp+M.score)/3)+"%",""],[BarChart3,"FREELANCE REVENUE",money(M.income),money(goals.income)+" target"],[ArrowUpRight,"TRADING ACCOUNT",money(M.balance),"P/L "+money(M.pl)],[Users,"ACTIVE CLIENTS",M.on.length,money(M.on.reduce((a,x)=>a+Number(x.mrr||0),0))+" MRR"]].map(([I,l,v,s])=><div className="card" key={l}><div className="label"><I size={12}/> {l}</div><div className="value">{v}</div><div className="sub">{s}</div></div>)}</div>
 <div className="section cols2"><div className="card"><div className="row"><h2>30-day execution</h2><span className="sub">Daily check-in score</span></div><div className="chart">{Array.from({length:30},(_,i)=>{let d=new Date();d.setDate(d.getDate()-(29-i));let x=checks.find(c=>c.date===d.toISOString().slice(0,10));let v=x?Math.round((x.priority_done+x.focus_done+x.no_impulsive)/3*100):0;return <div className="barcol" key={i}><i style={{height:Math.max(3,v)+"%"}}></i><span>{i===29?"Today":""}</span></div>})}</div></div><div className="card"><h2>Plan trajectory</h2>{[["Freelance income",M.ip],["Trading target",M.tp],["Today's execution",M.score]].map(([x,v])=><div className="progress" key={x}><div className="row"><span>{x}</span><b>{v}%</b></div><div className="bar"><i style={{width:v+"%"}}/></div></div>)}</div></div>
 <div className="section grid3"><div className="card"><h2>Today's execution</h2>{M.ci?<><div className="big">{M.score}%</div><p className="sub">{M.ci.hours||0}h freelance · {M.ci.proposals||0} proposals</p></>:<div className="empty">No check-in yet.<br/><br/><button className="btn" onClick={()=>setPage("checkin")}>Start check-in</button></div>}</div><div className="card"><h2>Trading discipline</h2><div className="big">{trades.length?Math.round(trades.filter(x=>x.followed_plan).length/trades.length*100):0}%</div><p className="sub">trades following plan</p><p>Win rate: <b>{trades.length?Math.round(M.wins.length/trades.length*100):0}%</b></p><p>Rule violations: <b className={M.viol?"negative":""}>{M.viol}</b></p></div><div className="card"><h2>Freelance funnel</h2><p>Proposals <b>{M.proposals}</b></p><p>Conversations <b>{M.convos}</b></p><p>New clients <b>{M.on.filter(x=>x.created_at?.startsWith(M.m)).length}</b></p></div></div></>}
 {page==="checkin"&&<><div className="top"><div><h1>Daily Check-in</h1><p className="muted">Record today's execution.</p></div></div><Form type="checkin"><div className="form"><div className="field"><label>Freelance hours</label><input type="number" step=".1" value={form.hours||""} onChange={e=>setForm({...form,hours:e.target.value})}/></div><div className="field"><label>Proposals sent</label><input type="number" value={form.proposals||""} onChange={e=>setForm({...form,proposals:e.target.value})}/></div><div className="field"><label>Client conversations</label><input type="number" value={form.conversations||""} onChange={e=>setForm({...form,conversations:e.target.value})}/></div><div className="field"><label>Freelance revenue ($)</label><input type="number" step=".01" value={form.revenue||""} onChange={e=>setForm({...form,revenue:e.target.value})}/></div><div className="field"><label>Trading P/L ($)</label><input type="number" step=".01" value={form.trading_pl||""} onChange={e=>setForm({...form,trading_pl:e.target.value})}/></div><div className="field"><label>Trading plan</label><select value={form.rules||"na"} onChange={e=>setForm({...form,rules:e.target.value})}><option value="yes">Followed</option><option value="no">Broke a rule</option><option value="na">Didn't trade</option></select></div><div className="full"><label><input type="checkbox" checked={!!form.priority_done} onChange={e=>setForm({...form,priority_done:e.target.checked})}/> Main priority completed</label><br/><label><input type="checkbox" checked={!!form.focus_done} onChange={e=>setForm({...form,focus_done:e.target.checked})}/> Focused work completed</label><br/><label><input type="checkbox" checked={!!form.no_impulsive} onChange={e=>setForm({...form,no_impulsive:e.target.checked})}/> No impulsive/revenge trading</label></div><div className="field full"><label>Notes</label><textarea rows="5" value={form.notes||""} onChange={e=>setForm({...form,notes:e.target.value})}/></div></div></Form></>}
 {page==="trades"&&<><div className="top"><div><h1>Trade Journal</h1><p className="muted">Every trade is stored in the database.</p></div></div><Form type="trade"><div className="form"><div className="field"><label>Pair</label><input value={form.pair||""} onChange={e=>setForm({...form,pair:e.target.value})}/></div><div className="field"><label>Direction</label><select value={form.direction||"Long"} onChange={e=>setForm({...form,direction:e.target.value})}><option>Long</option><option>Short</option></select></div><div className="field"><label>Entry</label><input type="number" value={form.entry||""} onChange={e=>setForm({...form,entry:e.target.value})}/></div><div className="field"><label>Exit</label><input type="number" value={form.exit||""} onChange={e=>setForm({...form,exit:e.target.value})}/></div><div className="field"><label>Position size ($)</label><input type="number" value={form.position_size||""} onChange={e=>setForm({...form,position_size:e.target.value})}/></div><div className="field"><label>Leverage</label><input type="number" value={form.leverage||1} onChange={e=>setForm({...form,leverage:e.target.value})}/></div><div className="field"><label>Risk ($)</label><input type="number" step=".01" value={form.risk||""} onChange={e=>setForm({...form,risk:e.target.value})}/></div><div className="field"><label>P/L ($)</label><input type="number" step=".01" value={form.pl||""} onChange={e=>setForm({...form,pl:e.target.value})}/></div><div className="field"><label>Strategy</label><input value={form.strategy||""} onChange={e=>setForm({...form,strategy:e.target.value})}/></div><div className="field"><label>Followed plan?</label><select value={form.followed_plan??"true"} onChange={e=>setForm({...form,followed_plan:e.target.value})}><option value="true">Yes</option><option value="false">No</option></select></div></div></Form><div className="section card"><h2>Trade history</h2><div className="tablewrap"><table className="table"><thead><tr><th>Date</th><th>Pair</th><th>Side</th><th>Lev</th><th>Risk</th><th>P/L</th><th>Plan</th></tr></thead><tbody>{trades.map(x=><tr key={x.id}><td>{x.trade_date}</td><td>{x.pair}</td><td>{x.direction}</td><td>{x.leverage}x</td><td>{money(x.risk)}</td><td className={x.pl>=0?"positive":"negative"}>{money(x.pl)}</td><td><span className="pill">{x.followed_plan?"Yes":"No"}</span></td></tr>)}</tbody></table></div></div></>}
 {page==="clients"&&<><div className="top"><div><h1>Clients & Revenue</h1><p className="muted">Onboard a client once; dashboard metrics update automatically.</p></div></div><Form type="client"><div className="form"><div className="field"><label>Client name</label><input value={form.name||""} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>Project</label><input value={form.project||""} onChange={e=>setForm({...form,project:e.target.value})}/></div><div className="field"><label>Project value ($)</label><input type="number" value={form.value||""} onChange={e=>setForm({...form,value:e.target.value})}/></div><div className="field"><label>Monthly recurring ($)</label><input type="number" value={form.mrr||""} onChange={e=>setForm({...form,mrr:e.target.value})}/></div><div className="field"><label>Source</label><select value={form.source||"Upwork"} onChange={e=>setForm({...form,source:e.target.value})}><option>Upwork</option><option>Referral</option><option>Direct</option><option>Other</option></select></div><div className="field"><label>Status</label><select value={form.status||"Onboarded"} onChange={e=>setForm({...form,status:e.target.value})}><option>Onboarded</option><option>Lead</option><option>Completed</option></select></div></div></Form><div className="section card"><h2>Clients</h2><div className="tablewrap"><table className="table"><thead><tr><th>Client</th><th>Project</th><th>Value</th><th>MRR</th><th>Status</th><th>Source</th></tr></thead><tbody>{clients.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.project}</td><td>{money(x.value)}</td><td>{money(x.mrr)}</td><td><span className="pill">{x.status}</span></td><td>{x.source}</td></tr>)}</tbody></table></div></div></>}
 {page==="goals"&&<><div className="top"><div><h1>Plan & Goals</h1><p className="muted">These targets drive the dashboard calculations.</p></div></div><Form type="goals"><div className="form"><div className="field"><label>Monthly freelance income target ($)</label><input type="number" value={form.income??goals.income} onChange={e=>setForm({...form,income:e.target.value})}/></div><div className="field"><label>Weekly proposals target</label><input type="number" value={form.proposals??goals.proposals} onChange={e=>setForm({...form,proposals:e.target.value})}/></div><div className="field"><label>Starting trading account ($)</label><input type="number" value={form.start??goals.start} onChange={e=>setForm({...form,start:e.target.value})}/></div><div className="field"><label>Trading target account ($)</label><input type="number" value={form.target??goals.target} onChange={e=>setForm({...form,target:e.target.value})}/></div><div className="field"><label>Daily execution target (%)</label><input type="number" value={form.score??goals.score} onChange={e=>setForm({...form,score:e.target.value})}/></div><div className="field"><label>Weekly freelance hours target</label><input type="number" value={form.hours??goals.hours} onChange={e=>setForm({...form,hours:e.target.value})}/></div></div></Form></>}
 <div className="footer">Growth OS · Dynamic Vercel + Supabase edition</div></main></div>
}